{% set name = "litellm" %}
{% set version = "1.89.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 8fcdb2b7a0ef3381d41adf164443842e31ef9f0cd5bcda6fc3c0bd8bc2959510

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - litellm = litellm:run_server
  skip: true # [py<310 or py>313]

requirements:
  host:
    - pip
    - python
    - uv-build >=0.9.7
  run:
    - python
    - fastuuid >=0.14.0,<1.0
    - httpx >=0.28.0,<1.0
    - openai >=2.20.0,<3.0.0
    - python-dotenv >=1.0.0,<2.0
    - tiktoken >=0.8.0,<1.0
    - importlib-metadata >=8.0.0,<9.0
    - tokenizers >=0.21.0,<1.0
    - click >=8.0.0,<9.0
    - jinja2 >=3.1.6,<4.0
    - aiohttp >=3.10,<4.0
    - pydantic >=2.10.0,<3.0.0
    - jsonschema >=4.0.0,<5.0
  run_constrained:
    - gunicorn >=23.0.0,<24.0
    - uvicorn >=0.33.0,<1.0
    - granian >=2.7.4,<3.0
    - uvloop >=0.21.0,<1.0  # [not win]
    - fastapi >=0.136.3,<1.0
    - starlette >=1.0.1,<2.0
    - backoff >=2.2.1,<3.0
    - pyyaml >=6.0.3,<7.0
    - rq >=2.7.0,<3.0
    - orjson >=3.11.6,<4.0
    - apscheduler >=3.11.2,<4.0
    - fastapi-sso >=0.19.0,<1.0
    - PyJWT >=2.12.0,<3.0
    - python-multipart >=0.0.27,<1.0
    - cryptography >=46.0.7,<47.0
    - pynacl >=1.6.2,<2.0
    - websockets >=15.0.1,<16.0
    - boto3 >=1.43.1,<2.0
    - azure-identity >=1.25.2,<2.0
    - azure-storage-blob >=12.28.0,<13.0
    - mcp >=1.26.0,<2.0
    - litellm-proxy-extras ==0.4.74
    - litellm-enterprise ==0.1.42
    - RestrictedPython >=8.1,<9.0
    - rich >=13.9.4,<14.0
    - polars >=1.38.1,<2.0
    - soundfile >=0.12.1,<1.0
    - pyroscope-io >=0.8.16,<1.0  # [not win]
    - pydantic-settings >=2.14.1,<3.0

# Tests removed: almost all of them are skipped in the end because of dependencies we don't have like fastapi_sso and others.
test:
  imports:
    - litellm
    - litellm.llms
    - litellm.proxy
    - litellm.proxy.hooks
  commands:
    - pip check
    - litellm --help
  requires:
    - pip
    - fastapi

about:
  home: https://github.com/BerriAI/litellm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Library to easily interface with LLM API providers
  description: |
    Translate inputs to provider's completion, embedding, and image_generation endpoints
    Consistent output, text responses will always be available at ['choices'][0]['message']['content']
    Retry/fallback logic across multiple deployments (e.g. Azure/OpenAI) - Router
    Track spend & set budgets per project LiteLLM Proxy Server
  dev_url: https://github.com/BerriAI/litellm
  doc_url: https://docs.litellm.ai/docs

extra:
  recipe-maintainers:
    - jan-janssen
